### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by ernie58** [1lobby/mailgun-js#56]
When i try to install 0.6.7 I get the following error:

	npm WARN unmet dependency /Users/bert/Sites/Kweetet-Diff/API/node_modules/mailgun-js/node_modules/path-proxy requires inflection@'~1.3.0' but will load
	npm WARN unmet dependency /Users/bert/Sites/Kweetet-Diff/API/node_modules/mailgun-js/node_modules/inflection,
	npm WARN unmet dependency which is version 1.5.3

**Comment by bojand** [comment]
Hello, what version of `npm` are you using? Does it happen with a clean `npm install` (ie. without any `node_modules` folder)? I cannot reproduce. This might be an issue with npm getting dependencies or cache confused or a bug if it's an older npm. I think there were issues like this one before.

**Comment by ernie58** [comment]
npm -v: -> 1.4.28
node: -> v0.10.35

It happens with a clean install, I delete the node_modules folder and run `sudo npm install`

**Comment by bojand** [comment]
Hmm. Can you try `npm cache clean` and then a clean install? Also what about mailgun-js `0.6.8`? ie if you try `npm install mailgun-js@0.6.8`. Finally can you add `--verbose` flag to the npm install command and paste the detailed logs please. for example `npm install mailgun-js@0.6.7 --verbose` (or v. 0.6.8).

**Comment by ernie58** [comment]
npm cache clean helped, thx a lot!
