### ISSUE TITLE
messages().send(data) should allow setting of headers and options

### ISSUE THREAD

**Issue by jonathanepollack** [1lobby/mailgun-js#57]
It would be awesome of I could give you arbitrary headers and options, that you would then transparently roll into the message posting.

e.g.

```
mailgun.messages().send({from: <sender>, 'h:Reply-To': <relay>, to: <recipient>})
```

**Comment by bojand** [comment]
Hello, that should already work. What version of the library are you using?
For example this works for me:
```
var params = {
  to: 'youremail@company.com',
  from: 'test@mailgun.com',
  'h:Reply-To': 'noreply@mailgun.com',
  subject: 'testing reply to',
  text: 'testing message'
};

mailgun.messages().send(params, function (err, body) {
  if (err) console.dir(err);
  console.dir(body);
});
```

The received email will have header `Reply-To: noreply@mailgun.com`, and clicking reply to will set the to email to `noreply@mailgun.com`.

**Comment by jonathanepollack** [comment]
Weird... I'm using `v0.6.7`. I found I was forced to do something like
```
mailgun.post(`/${domain}/messages`, params)
```
if I wanted to set heads (and optional variables).

**Comment by bojand** [comment]
Hmm same code as I posted above works for me with mailgun-js@0.6.7.
```
npm install mailgun-js@0.6.7
```

```
var mailgun = require('mailgun-js')({apiKey: <API_KEY>, domain: <DOMAIN>});

var params = {
  to: '<email>@<company>.com',
  from: 'test@mailgun.com',
  'h:Reply-To': 'noreply@mailgun.com',
  subject: 'testing replyto',
  text: 'testing message'
};

mailgun.messages().send(params, function (err, body) {
  if (err) console.dir(err);
  console.dir(body);
});
```

Hmm, I am not sure.

**Comment by jonathanepollack** [comment]
Sorry. Good call on closing this. I'll try to get a definitive example later but in the meanwhile, thanks for your work on this module!

**Comment by blairjo** [comment]
Hi,

Sorry to reopen a closed thread but I wasn't sure whether to do that or create a brand new one.
I am also having issues getting reply to working, on version 0.9.1

I have debugged the mailgun-js code as far as makind the request, and I can see that the reply to is present in the payload after the call to this.payload = qs.stringify(params);
Here is a short snippet:

```
html%3E%0A&h%3AReply-To=myEmail%40gmail.com&recipient-variables=
```
Note - I have replaced my email address with "myEmail" above.

When I look in the logs on the mailgun console, the reply to is not present in the header.
The only non-vanilla thing I'm doing is using recipient variables and [custom data variables](https://documentation.mailgun.com/user_manual.html#attaching-data-to-messages)
I wonder if either of those could be affecting this?

Thanks

**Comment by bojand** [comment]
can you please provide some code. thanks.

**Comment by blairjo** [comment]
sure, here is the code I'm using to send the mail:

``` js
function sendEmail(from, to, subject, templateArgs, html, recipientVariables, replyTo, bcc) {

  var replyToAddress = replyTo || from;

  var emailConfig = {
    from: from, 
    to: to, 
    subject: subject, 
    html: html
  };

  if(replyTo){
    emailConfig['h:Reply-To'] = replyTo;
  }

  if(bcc){
    emailConfig.bcc = bcc
  }

  if(recipientVariables){
    emailConfig['recipient-variables'] = recipientVariables;

    //standard fields that let us track webhooks

    if(templateArgs.year){
      emailConfig['v:year'] = templateArgs.year;
    }

    if(templateArgs.block){
      emailConfig['v:block'] = templateArgs.block;
    }

    if(templateArgs.settingId){
      emailConfig['v:settingId'] = templateArgs.settingId;
    }

    //if any recipient variable has child ids then assume they all do
    if(_.values(recipientVariables)[0].childIds) {
      emailConfig['v:childIds'] = '%recipient.childIds%';
    }


  }

  logger.debug('sending email using config: ', emailConfig);

  return mailgun.messages().send(emailConfig);

}
```

**Comment by blairjo** [comment]
Oh wait, sorry this is working..

My confusion was that I couldn't see anything related to the reply-to address in the mailgun logs, but when I actually press reply in my email client the reply address is correct.
I was expecting to see it in the headers section here:

```
"message": {
        "headers": {
            "to": "to@something.com",
            "message-id": "322432234232.234.234.234@something.com",
            "from": "from@something.com",
            "subject": "REMINDER - Parental Contract Form Outstanding"
        },
        "attachments": [],
        "size": 13794
    },
```

To further the confusion, it really wasn't working earlier today, because I was incorrectly specifying a "replyTo" property in my mailgun params, e.g

```
var emailConfig = {
    from: from, 
    to: to, 
    subject: subject,
    html: html,
   replyTo : replyTo
  };
```

Just a suggestion, it would be nice to have it there as a  first class citizen in a future release :)

Thanks for the prompt response, and sorry for wasting your time.

**Comment by javorosas** [comment]
I agree. We should have replyTo as a regular parameter. Fool-proof.

**Comment by bojand** [comment]
Hmm, the current API is in concert with the REST API. We support whatever params the API supports and you can pass anything in. Perhaps I am missing something, but I do not see the advantage of `replyTo` vs.`'h:Reply-To'`. It breaks the existing consistency and the expectation of how things should work.

**Comment by blairjo** [comment]
Hi @bojand 
It's a fair point, and I can understand why you want to keep it as per the mailgun api, I just found it odd in the first place that mailgun didn't allow you to specify replyTo as a regular param ( the way that say nodemailer does ).
I thought it could be a useful ease of use feature for your library to add it as a first class citizen rather then having to remember the quite clunky h:Reply-To syntax.

Up to you though :)

**Comment by kgrosvenor** [comment]
@blairjo  i agree, it's logical and would be a nicer api on the client, which then passes the h:Reply-To from using replyTo
