### ISSUE TITLE
Receive email?

### ISSUE THREAD

**Issue by bl0zis** [1lobby/mailgun-js#58]
Hello,
It is possible to receive mail with this?

**Comment by bojand** [comment]
Hello,

I am not sure what you mean. You can receive emails through Mailgun, [as documented.](https://documentation.mailgun.com/user_manual.html#receiving-forwarding-and-storing-messages) You can use `mailgun-js` to programmatically set up `Routes` and actions if needed, but that can be done using the Mailgun dashboard as well. Then you can forward the received messages to another email address or URL. In case of URL, see [securing webhooks](https://documentation.mailgun.com/user_manual.html#webhooks). `mailgun-js` offers a [helper function for this](https://github.com/1lobby/mailgun-js#webhook-validation). Hope this helps.

**Comment by bl0zis** [comment]
@bojand 
Thank you very much, for examples on a test folder.

**Comment by bl0zis** [comment]
When I try to send mail from Gmail, I have and error :x: 

> Delivery to the following recipient failed permanently:
hello@euroconflict.org<br/>
Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain euroconflict.org by mxa.mailgun.org. [104.130.177.23].<br/><br/>The error that the other server returned was:
550 5.1.0 Recipient rejected: <hello@euroconflict.org>

But my route has good configuration

```
mailgun.routes().create({
      description: 'all',
      expression: 'match_recipient(".*@euroconflict.org")',
      action: 'forward("xxxx@xxxxxxxx")'
});

```

**Comment by bojand** [comment]
Hmm not sure if this is an issue with `mailgun-js`, or Mailgun at all, for that matter, or just something with the specifics of your code and setup. Will have to look into it, but I'm busy / away for a little while so it will have to wait a week or two.

**Comment by bl0zis** [comment]
@bojand  Hello, I asked the support of Mailgun about this problem, and it is really their problem because of changes on the service, and it looks like the problem is solved now!
Thanks!

**Comment by roccomuso** [comment]
I'm getting the same error... why?
