### ISSUE TITLE
How to add custom data to messages.

### ISSUE THREAD

**Issue by winduptoy** [1lobby/mailgun-js#60]
This is not documented for this library.

See here: https://documentation.mailgun.com/user_manual.html#attaching-data-to-messages

**Comment by bojand** [comment]
Hello, I am not sure I understand what is exactly the issue? We certainly do not try to document the whole API, hence the first link the the read me is to the Mailgun's own API documentation. The readme just shows how to use the API, and some specific things and special cases. The library can take any parameter data for requests, including custom data for messages. Is this not clear in the existing readme? Or do you feel that a special note regarding adding custom data to messages is warranted to be in the readme? Just trying to actually understand the issue and where confusion actually is.

**Comment by winduptoy** [comment]
@bojand I am confused on how to add custom data to my messages. The official API docs says:

> Pass the following parameter, `“v:my-custom-data” => “{“my_message_id”: 123}”`.

How do I do that using mailgun-js?

I have tried the following with no success.

```javascript
var data = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: 'serobnic@mail.ru',
  subject: 'Hello',
  text: 'Testing some Mailgun awesomness!',
  'v:my-custom-data': {whatever: 123, test: true}
};

mailgun.messages().send(data ......
```

**Comment by bojand** [comment]
Not sure exactly what your use case is, but this should work:

```js
var data = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: 'serobnic@mail.ru',
  subject: 'Hello',
  text: 'Testing some Mailgun awesomness!',
  'v:whatever': 123,
  'v:test': true
};
```

Or you can manually JSON stringify the object if that's desired:

```js
var data = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: 'serobnic@mail.ru',
  subject: 'Hello',
  text: 'Testing some Mailgun awesomness!',
  'v:my-custom-data': JSON.stringify({whatever: 123, test: true})
};
```

Perhaps the library should do that automatically in case of objects.

I will add support to automatically stringify `v:*` param objects soon.

**Comment by winduptoy** [comment]
@bojand Thanks, that fixes it. It was unclear that setting `v:my-custom-data` needed to be stringified.
