### ISSUE TITLE
cc and bcc

### ISSUE THREAD

**Issue by murindwaz** [1lobby/mailgun-js#62]
Is it possible to send copy carbon, and blind copy carbon?
The current implementation doesn't seem to send one message to two recipients, unless you use a mailing list

**Comment by bojand** [comment]
Hello, yes it is possible to pass in `cc` and `bcc` fields. Also params can be arrays. Something like:
```js
var params = {
  to: ['address1@company.com', 'address2@company.com']
  cc: ['address3@company.com', 'address4@company.com'],
  bcc: ['address5@company.com', 'address6@company.com'],
  from: 'me@company.com',
  subject: 'testing mailgun',
  text: 'test message for mailgun'
};

mailgun.messages().send(params, function (err, body) {
  if (err) console.dir(err);
  console.dir(body);
});
```

**Comment by sadeqzadeh** [comment]
What about MIME types? Can one have CC and BCC in an email with HTML body? It seems it's not possible since you have to explicitly set "to" field after mailComposer builds the message:

`mailComposer.buildMessage(function(mailBuildError, messageSource) {
    var dataToSend = {
      to: content.recipients[0],
      message: messageSource
    };

    mgSender.messages().sendMime(dataToSend, function (error, response) {`

**Comment by dmolineuxcb** [comment]
It appears `to` cannot be an array, showing this error:
