### ISSUE TITLE
Webhook Validation Issue

### ISSUE THREAD

**Issue by winduptoy** [1lobby/mailgun-js#64]
I'm validating my webhooks [exactly as described in the README](https://github.com/1lobby/mailgun-js#webhook-validation).

Delivered messages, clicks, and opens are working flawlessly. However, when I receive requests for dropped messages, hard bounces, and spam complaints, I'm getting the following in my console:

```
[mailgun] Stale Timestamp: this may be an attack
[mailgun] However, this is most likely your fault

[mailgun] run `ntpdate ntp.ubuntu.com` and check your system clock

[mailgun] System Time: Thu Mar 26 2015 17:30:54 GMT-0400 (EDT)
[mailgun] Mailgun Time: Invalid Date undefined
[mailgun] Delta: NaN
```

I decided to log the body of the request, to see what Mailgun was actually returning, but it turned out to be an empty (logging the body of the request for delivered messages, clicks, and opens shows exactly what one would expect). This is an issue with Mailgun, right? Am I missing something?

**Comment by winduptoy** [comment]
Contacted Mailgun support. Turns out that delivered messages, clicks, and opens return `application/x-www-form-urlencoded` content type requests while dropped messages, hard bounces, and spam complaints all return `multipart/form-data` content type requests. :stuck_out_tongue:

**Comment by mikemclin** [comment]
FYI, for anyone that setup inbound emails to forward to their app via Mailgun Routes, validation will fail if the incoming email has an attachment.  You will need to use the "Store and notify" setting in your Mailgun Route config, not the "Forward" setting.
