### ISSUE TITLE
Request Entity Too Large error

### ISSUE THREAD

**Issue by helloworld** [1lobby/mailgun-js#67]
I am making this request: 

    var filepath = path.join(__dirname, "/output/" + job.jobId + ".zip");

    var data = {
        from: 'Name <name@url.com>',
        to: email,
        subject: 'Test',
        text: 'Test',
        attachment: filepath
    };

    mailgun_client.messages().send(data, function(error, body) {
        if(error) console.log(error)
        console.log(body);
    });

and am getting this error: 

    { [Error: <html>
    <head><title>413 Request Entity Too Large</title></head>
    <body bgcolor="white">
    <center><h1>413 Request Entity Too Large</h1></center>
    <hr><center>nginx/1.7.9</center>
    </body>
    </html>
    ] statusCode: 413 }

How do I fix this? Is it because the attachment is too big?

**Comment by bojand** [comment]
Seems likely. How big is the attachment?

https://documentation.mailgun.com/user_manual.html#sending-messages

```
Note: Mailgun supports maximum messages size of 25MB.
```
