### ISSUE TITLE
Error('"name" and "value" are required for setHeader()?

### ISSUE THREAD

**Issue by lmessinger** [1lobby/mailgun-js#68]
Hi
I get the above error
when i run mailgun.messages().send in the code:
var data = {
       from: locals.owner.firstName + " " + locals.owner.lastName + "<" + locals.owner.email + ">",
       to: user.email,
       subject: locals.process.processName ,
       text: locals.process.emailTemplate,
       attachment: filepath
     };

     mailgun.messages().send(data, function (error, body) {
       console.log(index,error,body);
       if (error) {
         cbFunc(error);
       }
     });

any ideas?

thanks very much!

**Comment by bojand** [comment]
Hmm are you sure this is coming from mailgun-js or mailgun service? Not really sure... this error message seems really strange. Don't think it would come from this mailgun library. I cannot reproduce it.

**Comment by lmessinger** [comment]
I'm sorry, I can report it was my bug - the file attachment path was wrong. not sure why it led to that. it was mailgun-js. thanks for the prompt response
