### ISSUE TITLE
this module is currently unusable due to dependency node-degenerator

### ISSUE THREAD

**Issue by abelino** [1lobby/mailgun-js#69]
please see https://github.com/npm/npm/issues/8641

because of node module degenerator, mailgun-js does not install at all. Please remove that dependency and/or find a suitable replacement.

**Comment by tgriesser** [comment]
Related: https://github.com/TooTallNate/node-degenerator/pull/6

**Comment by tgriesser** [comment]
@abelino btw, if you fork/patch package.json and install degenerator top level at that git commit it'll work. I'd say use mine but it's likely i'll delete the repo after this gets upstreamed :)

```js
"degenerator": "tgriesser/node-degenerator.git#34ddcee6a7431149f6734fc4fe7f80d27a1e0c1b",
```

**Comment by abelino** [comment]
I was just about to comment that... hehe Yea I also ran the mocha tests and everything checked out:

$ mocha test/test.js 


  degenerator()
    "expected" fixture tests
      ✓ basic.js → basic.expected.js
      ✓ get-example.js → get-example.expected.js
      ✓ multiple.js → multiple.expected.js
      ✓ pac-resolver-gh-3.js → pac-resolver-gh-3.expected.js


  4 passing (43ms)

**Comment by abelino** [comment]
@tgriesser send a pull request

**Comment by bojand** [comment]
Unfortunately a lot of packages are being affected by this issue with degenerator. Hopefully we'll have a fix soon. I'll see what I can do to resolve here if it's not fixed in the dependency, but probably won't be able to get to it in a few hours.

**Comment by garrett-gottlieb** [comment]
+1

**Comment by abelino** [comment]
degenerator v1.0.2 has been published with dependency fix
https://github.com/TooTallNate/node-degenerator/pull/6

**Comment by bojand** [comment]
seems to be working ok for me now.
