### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by SethHamilton** [1lobby/mailgun-js#71]
Is there a way to set (or add) a timeout on a connection. We are sending millions of emails via MailGun, and occasionally our message pump (which simply drains a redis list with prepared content), hangs in the call to message().send. It just never calls the callback. It's intermittent, we can send 100k emails or millions and then it pops up. My thoughts are that something went wrong the connection and it needs to timeout, or a callback is being missed somewhere in mailgun-js and node goes idle (our status monitor for example keeps running). Any ideas?

**Comment by bojand** [comment]
Hello,

Hmm that does sound strange. Are you using a proxy? Are there attachments? Can you post some sample code / pseudo code on how you are using the library just so I understand the context? Are emails sent asynchronously in parallel? or synchronously in a series. If parallel, how many at a time?

I think a timeout option is possible. We can just use the normal http(s) Request `setTimeout` option.

https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback

I am thinking that the timeout from http will result with err in the callback from mailgun library.

so for example something like:

```
var mailgun = require('mailgun-js')({
  apiKey: api_key, 
  domain: mydomain, 
  timeout: 60000 // 1 minute timeout
}); 

var data = {
  //...
};
 
mailgun.messages().send(data, function (err, body) {
  if(err) {
    console.log(err); // in case of timeout err will be defined with some kind of timeout message and passed back in the callback
  }
  console.log(body);
});
```

Any thoughts? Does this sound sensible?

**Comment by SethHamilton** [comment]
I am sending up to 8 at a time, the code is simple. There is a function that waits on blpop from redis, when it pops, it takes the content and pushes it to message.send(). When message.send returns, it calls itself using setimmediate to unroll any stack.

At startup I call the function 8 times, which basically puts 8 calls waiting on blpop. 

It's an odd one, it can run for weeks and send millions of emails, or like in the last few days stop 3 times. It's now running smoothly again, which makes me think it's a "hung" connection. 

I'm thinking the timeout as you specified would be perfect just to catch anything along these lines, and you are correct, request does have a timeout option, so if you can use that, it makes perfect sense.

Thank you for looking into this, and we really enjoy this module, it great.
Seth
