### ISSUE TITLE
[SyntaxError: Unexpected end of input]

### ISSUE THREAD

**Issue by camwhite** [1lobby/mailgun-js#73]
I am trying to add users to a mailing list, but I am seeing the error mentioned in the title. Although, to my understanding my code should work as expected. The code looks as follows..

```
var config = require('../../config/environment');

var api_key = config.mailgun.apiKey;
var domain = config.mailgun.domain;

var Mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});

exports.subscribe = function(req, res) {
  var members = [req.body]
  Mailgun.lists('mesh@sandbox7626287abc2d424788b2279cb1808c09.mailgun.org').members().add({
    members: members, 
    subscribed: true
  }, function(err, body) {
    if(err) { return  res.send(err); }
    return res.send(200);
  });
};
```

The request body is the object `{address: foo@foo.com}`

I'm pretty positive it's something that is staring me right in the face, but I can't find the light in all this darkness. Any help would be much appreciated!

Update:

Ok I figured out I needed to be making a GET request and shoving the email into the params. No errors now, but I'm not seeing any users being added to list. Also, the body param in the callback logs out undefined.

**Comment by bojand** [comment]
Sorry I am not understanding what's the issue...? "Make GET request"? Please try the latest version of module. In case of error please provide node and npm versions and exact error details. Reproducible source code would also help. `add()` functionality is tested in [tests](https://github.com/1lobby/mailgun-js/blob/master/test/mailgun.test.js#L846).
