### ISSUE TITLE
Public end points

### ISSUE THREAD

**Issue by rick4470** [1lobby/mailgun-js#76]
From looking over the test's, it does not seem like public end points are supported. 

I want to be able to do something like this.

```javascript
mailgun.post("/address/validate", {
  address: 'hello@bar.com'
}, function (error, response) {});
```

This is the public end point `api.mailgun.net/v3/address/validate` [docs](https://documentation.mailgun.com/api-email-validation.html#email-validation)
And this is what my current solution looks like

```javascript
var url = "https://api:" + this.publicKey + "@api.mailgun.net/v3/address/validate";
request({
  url: url,
  form: {
    address: encodeURI(email)
  }
}, function (error, response, data) {
  if (error) {
    defer.reject(error);
  }
  defer.resolve(data);
});
```

**Comment by bojand** [comment]
Need to use GET...

```
mailgun.get('/address/validate', { address: 'foo@mailgun.net' }, function(err, body) {
  if (err) console.dir(err);
  console.dir(body);
  process.exit(0);
});
```
Output:
```
{ address: 'foo@mailgun.net',
  did_you_mean: null,
  is_valid: true,
  parts: { display_name: null, domain: 'mailgun.net', local_part: 'foo' } }
```

**Comment by rick4470** [comment]
Thanks for responding to this issue, unfortunately it's not working correctly.

Here is the output: `[SyntaxError: Unexpected end of input]`

How can I set the public key?

**Comment by bojand** [comment]
Just create anther instance of mailgun.
```
var mailgun2 = require('mailgun-js')({apiKey: 'pubkey-xyz123', domain: domain});
```

or if you already have an instance:
```
var mailgun2 = new mailgun.Mailgun({
  domain: auth.domain,
  apiKey: 'pubkey-xyz123'
});
```
