### ISSUE TITLE
Add retry mechanism to retry sending emails due to network failure

### ISSUE THREAD

**Issue by rahul8590** [1lobby/mailgun-js#80]
I was wondering, if mailgun-js could support no of times to retry as one of the options in mailgun. For example,

```js
var mailgun = require('mailgun-js')({
                      apiKey: api_key, 
                      domain: domain,
                      timeout: 2000,
                      retry: 3 });
```
Its trivial to implement as a retry callback function. But it ll be lot neater to have this option integrated within mailgun.

**Comment by bojand** [comment]
Implemented with pull request #83
