### ISSUE TITLE
Attachments no longer get attached

### ISSUE THREAD

**Issue by nullfox** [1lobby/mailgun-js#81]
As of yesterdays commit, attachments are no longer sent to Mailgun. It looks like the change to prepareData checks for and ignores attachment and inline keys: https://github.com/1lobby/mailgun-js/commit/ef904c0721de5f02a43ad53ea7d2dcf34960ad00#diff-96d9811cb2296e877edf463c6cfc57bdR109

With params no longer containing an attachment key, the if statement here fails and never calls prepareFormData: https://github.com/1lobby/mailgun-js/commit/ef904c0721de5f02a43ad53ea7d2dcf34960ad00#diff-96d9811cb2296e877edf463c6cfc57bdR53

**Comment by bojand** [comment]
Sorry don't know how I missed that in my tests. Should be fixed now. Please let me know if it's still an issue.
