### ISSUE TITLE
Not able to send messages

### ISSUE THREAD

**Issue by benrlodge** [1lobby/mailgun-js#85]
I was able to successfully use mailgun-js to add someone to a mailing list, but I'm running into an error (404) sending a message. Sounds like the endpoint may not be configured properly? 

Note - I was able to send an email using the curl example in [the api docs](https://documentation.mailgun.com/api-sending.html#examples), so I don't think it's an issue with my DNS settings. 

Code used:
```javascript

var api_key = MY_KEY;
var domain = 'https://api.mailgun.net/v3/WWW.MYSITE.COM';
var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});

    var data = {
      from: 'Me <me@me.com>',
      to: 'example_email@something.com',
      subject: 'Hello',
      html: 'oh hi'
    }

    mailgun.messages().send(data, function (err, body) {
        if (err) {
          console.log("got an error: ", err);
        }
    });
```

error: 
```
127.0.0.1 - - [20/Dec/2015:20:52:16 +0000] "POST /api/v1/subscribe HTTP/1.1" 200 25 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
got an error:  { [Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>
] statusCode: 404 }
Message sent: 250 2.0.0 OK 1450644728 y129sm11413404qka.33 - gsmtp
```

**Comment by bojand** [comment]
The `domain` param should just be your mailgun domain not a full url. so in the case of your sample code just `'WWW.MYSITE.COM'`.

**Comment by benrlodge** [comment]
Ah great thanks @bojand that worked. This is real strange though, how come I was able to get the mailing list method to work, as I used the full url??

This worked fine:
```javascript
var api_key = 'KEYHERE';
var domain = 'https://api.mailgun.net/v3/www.my-website.com';
var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});


function MailingList(settings) {
  this.list = mailgun.lists(settings.list);
}

MailingList.prototype = {

  create: function(payload){
    this.list.members().create(payload, function (err, data) {
      // worked...
    });
  }

}
```

**Comment by benrlodge** [comment]
In any case, this resolves my issues, thanks for the guidance.

**Comment by timsvoice** [comment]
@bojand thanks for the answer. Would you consider an update to the docs? It's a little confusing as the `var domain = 'mydomain.mailgun.org';` seems to indicate that we should use something other than the simple domain name.

**Comment by adamkdean** [comment]
@bojand thanks for the answer too. Docs definitely lacking in this case.
