### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by gfarrell** [1lobby/mailgun-js#87]
I'm trying to send an attachment via `mailgun-js`. When there were no attachments, it worked fine, but now I'm getting `ECONNRESET`:

```
Error: socket hang up
        at createHangUpError (_http_client.js:209:15)
        at TLSSocket.socketOnEnd (_http_client.js:294:23)
        at emitNone (events.js:72:20)
        at TLSSocket.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:905:12)
        at nextTickCallbackWith2Args (node.js:455:9)
        at process._tickCallback (node.js:369:17)
```

Nothing appears in the mailgun dashboard logs.

**Comment by bojand** [comment]
All tests pass and attachments work fine in my test code. Please provide sample code that reproduces the problem.

**Comment by gfarrell** [comment]
It stopped happening after I started using streams to create the attachments (although I now have a different problem).

**Comment by shakvaal** [comment]
I'm constantly having the "Socket hang up" problem and it seems like the problem occurs randomly - a test script run several times can bear different results.

**Comment by k9982874** [comment]
i get the same issue, need help

**Comment by ahmismail** [comment]
Same issue here, any help?

**Comment by ajouve** [comment]
I had the same issue, I was getting a remote file as attachement

```js
const attachement = request('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png')
```

And I was returning the datas I had to send with mailgun using a function.

To fix it, you should use `mailgun.messages().send(message)` in the same function that you instanciate request
