### ISSUE TITLE
Attachments from a readable stream not being attached

### ISSUE THREAD

**Issue by gfarrell** [1lobby/mailgun-js#88]
I am using `event-stream` and `csv` to create a readable stream of CSV data to attach to an email (see http://stackoverflow.com/questions/34769574/using-streams-to-pipe-data-in-node-js).

I have verified (using the `csvStream.on("data", ...)` event) that the data are coming out correctly, so the stream itself is not devoid of data (and they are correct CSV records).

I am creating the attachment as follows:

```javascript
const attachment = new Attachment({
    data:        csvStream,
    file:        `${strName}.csv`,
    contentType: "text/csv"
});
```

Which is being passed as `attachment` in the `data` object.

When I look in the mailgun logs, it shows `"attachments": [],`, which would explain why I can't see an attachment in the emails (mailgun isn't receiving one), yet `data.attachment` is definitely there as in the docs.

**Comment by bojand** [comment]
As the documentation states `knownLength` is required parameter to `Attachment` constructor in case of a stream attachment, which specifies the actual byte size of payload, so you need to provide that, and I don't think you know that ahead of time... If you run with `DEBUG=*` or `DEBUG=mailgun-js` you should get output similar to:

```
mailgun-js missing content type or length for attachment stream. key: attachment
```
Also, csv-stringify implements a Transform stream (and not just a Readable), so I am not sure if that would work out of the box as intended.

I read the link on SO... why can't you just attach the string or Buffer data something like:

```
var stringify = require('csv-stringify');

data = '';
stringifier = stringify()
stringifier.on('readable', function(){
  while(row = stringifier.read()){
    data += row;
  }
});
stringifier.on('error', function(err){
  consol.log(err.message);
});
stringifier.on('finish', function(){
  var attachment = new Attachment({
    data:        data,
    file:        `${strName}.csv`,
    contentType: "text/csv"
  });
  // send it..
});
```

**Comment by gfarrell** [comment]
Is there a reason that `mailgun-js` doesn't throw if the data are invalid? Silent errors make it quite hard to debug.

I'm not using `concat-stream` to concatenate the data for sending, although I was using streams in the first place to avoid loading the entire dataset into memory but it's not a big deal for the moment.

You're right that I can't know the byte length ahead of time, so concatenation is my only option it seems (other than writing to a file).

Problem resolved in that case (although it would be nice to have louder errors).
