### ISSUE TITLE
Multiple Attachments

### ISSUE THREAD

**Issue by Zambonilli** [1lobby/mailgun-js#93]
How would you add multiple attachments in a single email?

**Comment by bojand** [comment]
As the readme states:

```
Multiple attachments can be sent by passing an array in the attachment parameter. 
The array elements can be of any one of the valid types and each one will be handled appropriately.
```

Also [sample code in tests](https://github.com/1lobby/mailgun-js/blob/master/test/mailgun.test.js#L148).

**Comment by Zambonilli** [comment]
Fantastic, thank you!
